# 4.7 Deriving New Variables
### Price label variables
### Busiest days of the week variable
### Busiest hours of the day variables
### Exporting data

In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import os

In [2]:
path = r"C:\Users\cavba\Documents\Instacart Basket Analysis"

In [3]:
df_ords_prods_merged = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged.pkl'))

In [4]:
df_ords_prods_merged.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,11,3.0,5,0,both
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,17,20.0,1,1,both
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,21,6.0,20,0,both
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,prior,1,3,13,NaN,10,0,both
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,17,9.0,11,1,both

In [5]:
df_ords_prods_merged.shape

(32404859, 15)

In [8]:
df = df_ords_prods_merged[:1000000]

In [9]:
df.shape

(1000000, 15)

## Price label variables

In [10]:
#Defining price_label variable
def price_label(row):

  if row['prices'] <= 5:
    return 'Low-range product'
  elif (row['prices'] > 5) and (row['prices'] <= 15):
    return 'Mid-range product'
  elif row['prices'] > 15:
    return 'High range'
  else: return 'Not enough data'

In [11]:
df['price_range'] = df.apply(price_label, axis=1)

<ipython-input-11-fe64de1169c8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_range'] = df.apply(price_label, axis=1)

In [12]:
df['price_range'].value_counts(dropna = False)

Mid-range product    652638
Low-range product    338018
High range             9344
Name: price_range, dtype: int64

In [13]:
# Finding the maximum value withint the prices column
df['prices'].max()

24.5

In [14]:
# If-statements with the loc function
df.loc[df['prices']> 15, 'price_range_loc'] = 'High-range product'

C:\Users\cavba\anaconda3\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
C:\Users\cavba\anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [15]:
df.loc[(df['prices']<= 15) & (df['prices']> 5), 'price_range_loc'] = 'Mid-range product'

C:\Users\cavba\anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [16]:
df.loc[df['prices']<= 5, 'price_range_loc'] = 'Low-range product'

C:\Users\cavba\anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [17]:
df['price_range_loc'].value_counts(dropna = False)

Mid-range product     652638
Low-range product     338018
High-range product      9344
Name: price_range_loc, dtype: int64

In [18]:
#high-range function
df_ords_prods_merged.loc[df_ords_prods_merged['prices']> 15, 'price_range_loc'] = 'High-range product'

In [19]:
#Mid-range function
df_ords_prods_merged.loc[(df_ords_prods_merged['prices']<= 15) & (df_ords_prods_merged['prices']> 5), 'price_range_loc'] = 'Mid-range product'

In [20]:
# Low range function
df_ords_prods_merged.loc[df_ords_prods_merged['prices']<= 5, 'price_range_loc'] = 'Low-range product'

In [21]:
df_ords_prods_merged['price_range_loc'].value_counts(dropna = False)

Mid-range product     21860860
Low-range product     10126321
High-range product      417678
Name: price_range_loc, dtype: int64

In [22]:
df_ords_prods_merged['order_dow'].value_counts(dropna = False)

0    6204182
1    5660230
6    4496490
2    4213830
5    4205791
3    3840534
4    3783802
Name: order_dow, dtype: int64

In [23]:
result = []

for value in df_ords_prods_merged['order_dow']:
    if value == 0:
        result.append("Busiest day")
    elif value == 4:
        result.append("Least busy")
    else:
        result.append("Regular busy")

In [24]:
#shorten dataframe name
ords_prods_merge = df_ords_prods_merged

In [25]:
result[:20]

['Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy']

In [26]:
ords_prods_merge['busiest day'] = result

In [27]:
# frequency check
ords_prods_merge['busiest day'].value_counts(dropna = False)

Regular busy    22416875
Busiest day      6204182
Least busy       3783802
Name: busiest day, dtype: int64

In [28]:
#fixing data that didn't save prior/ renaming order_dow column
df_ords_prods_merged.rename(columns={'order_dow':'orders_day_of_the_week'}, inplace = True)

In [29]:
ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,orders_day_of_the_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest day
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,11,3.0,5,0,both,Mid-range product,Regular busy
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,17,20.0,1,1,both,Mid-range product,Regular busy
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,21,6.0,20,0,both,Mid-range product,Busiest day
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,prior,1,3,13,NaN,10,0,both,Mid-range product,Regular busy
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,17,9.0,11,1,both,Mid-range product,Least busy

In [30]:
ords_prods_merge.drop(columns=['eval_set'])

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_the_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest day
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid-range product,Regular busy
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid-range product,Regular busy
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid-range product,Busiest day
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Mid-range product,Regular busy
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid-range product,Least busy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32404854,49688,Fresh Foaming Cleanser,73,11,13.5,1788356,200215,2,0,9,5.0,27,0,both,Mid-range product,Busiest day
32404855,49688,Fresh Foaming Cleanser,73,11,13.5,3401313,200377,1,4,11,NaN,5,0,both,Mid-range product,Least busy
32404856,49688,Fresh Foaming Cleanser,73,11,13.5,809510,200873,5,3,8,15.0,12,0,both,Mid-range product,Regular busy
32404857,49688,Fresh Foaming Cleanser,73,11,13.5,2359893,200873,9,3,15,5.0,11,1,both,Mid-range product,Regular busy
32404858,49688,Fresh Foaming Cleanser,73,11,13.5,2385091,205926,11,1,15,6.0,35,0,both,Mid-range product,Regular busy

In [31]:
ords_prods_merge.shape

(32404859, 17)

# 4.7 Task Answers

## Daily order frequency

In [32]:
# getting frequency for each day
ords_prods_merge['orders_day_of_the_week'].value_counts(dropna = False)

0    6204182
1    5660230
6    4496490
2    4213830
5    4205791
3    3840534
4    3783802
Name: orders_day_of_the_week, dtype: int64

Two busiest days are Sunday (0) and Monday (1). Slowest days are Wednesday (3) and Thursday (4)

## Deriving busiest days variables

In [33]:
#if-statement with for-loop grouping busiest, slowest, and regular days
result = []

for value in ords_prods_merge['orders_day_of_the_week']:
    if value <=1:
        result.append('busiest days')
    elif value ==3 or value ==4:
        result.append('slowest days')
    else:
        result.append('regular days')

In [34]:
ords_prods_merge['Result'] = result

In [35]:
ords_prods_merge['Result'].value_counts(dropna = False)

regular days    12916111
busiest days    11864412
slowest days     7624336
Name: Result, dtype: int64

The order frequency for regular days isn't much higher than the busiest days even though there are twice as many regular days.

## Step 3

In [36]:
# checking to make sure if-statement worked properly
ords_prods_merge.tail(50)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,orders_day_of_the_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest day,Result
32404809,49688,Fresh Foaming Cleanser,73,11,13.5,2732438,111542,prior,10,0,21,5.0,3,0,both,Mid-range product,Busiest day,busiest days
32404810,49688,Fresh Foaming Cleanser,73,11,13.5,2996443,114963,prior,12,1,14,16.0,19,0,both,Mid-range product,Regular busy,busiest days
32404811,49688,Fresh Foaming Cleanser,73,11,13.5,891179,118871,prior,7,1,9,2.0,4,0,both,Mid-range product,Regular busy,busiest days
32404812,49688,Fresh Foaming Cleanser,73,11,13.5,3290206,121646,prior,3,0,9,14.0,10,0,both,Mid-range product,Busiest day,busiest days
32404813,49688,Fresh Foaming Cleanser,73,11,13.5,2951582,124944,prior,6,0,15,30.0,12,0,both,Mid-range product,Busiest day,busiest days
32404814,49688,Fresh Foaming Cleanser,73,11,13.5,328141,128148,prior,3,0,11,7.0,10,0,both,Mid-range product,Busiest day,busiest days
32404815,49688,Fresh Foaming Cleanser,73,11,13.5,3041952,128148,prior,28,0,11,5.0,1,1,both,Mid-range product,Busiest day,busiest days
32404816,49688,Fresh Foaming Cleanser,73,11,13.5,1897157,128930,prior,7,0,16,30.0,14,0,both,Mid-range product,Busiest day,busiest days
32404817,49688,Fresh Foaming Cleanser,73,11,13.5,2476113,128930,prior,9,5,13,30.0,7,1,both,Mid-range product,Regular busy,regular days
32404818,49688,Fresh Foaming Cleanser,73,11,13.5,1631554,129901,prior,2,5,11,30.0,23,0,both,Mid-range product,Regular busy,regular days
32404819,49688,Fresh Foaming Cleanser,73,11,13.5,641382,142639,prior,26,5,14,30.0,6,0,both,Mid-range product,Regular busy,regular days
32404820,49688,Fresh Foaming Cleanser,73,11,13.5,253490,144914,prior,16,1,8,9.0,20,0,both,Mid-range product,Regular busy,busiest days
32404821,49688,Fresh Foaming Cleanser,73,11,13.5,965803,145111,prior,1,3,17,NaN,20,0,both,Mid-range product,Regular busy,slowest days
32404822,49688,Fresh Foaming Cleanser,73,11,13.5,393166,145526,prior,23,1,11,11.0,34,0,both,Mid-range product,Regular busy,busiest days
32404823,49688,Fresh Foaming Cleanser,73,11,13.5,3058519,145732,prior,4,0,8,19.0,8,0,both,Mid-range product,Busiest day,busiest days
32404824,49688,Fresh Foaming Cleanser,73,11,13.5,3122003,146323,prior,3,1,16,24.0,20,0,both,Mid-range product,Regular busy,busiest days
32404825,49688,Fresh Foaming Cleanser,73,11,13.5,2779979,151977,prior,1,0,16,NaN,8,0,both,Mid-range product,Busiest day,busiest days
32404826,49688,Fresh Foaming Cleanser,73,11,13.5,2363598,153612,prior,1,6,11,NaN,1,0,both,Mid-range product,Regular busy,regular days
32404827,49688,Fresh Foaming Cleanser,73,11,13.5,967902,157883,prior,3,0,17,30.0,6,0,both,Mid-range product,Busiest day,busiest days
32404828,49688,Fresh Foaming Cleanser,73,11,13.5,2932449,159099,prior,2,2,14,15.0,3,0,both,Mid-range product,Regular busy,regular days
32404829,49688,Fresh Foaming Cleanser,73,11,13.5,2744037,159487,prior,1,2,18,NaN,2,0,both,Mid-range product,Regular busy,regular days
32404830,49688,Fresh Foaming Cleanser,73,11,13.5,13797,159487,prior,8,0,12,14.0,2,1,both,Mid-range product,Busiest day,busiest days
32404831,49688,Fresh Foaming Cleanser,73,11,13.5,258779,159487,prior,11,2,20,17.0,2,1,both,Mid-range product,Regular busy,regular days
32404832,49688,Fresh Foaming Cleanser,73,11,13.5,311401,159487,prior,13,4,18,30.0,1,1,both,Mid-range product,Least busy,slowest days
32404833,49688,Fresh Foaming Cleanser,73,11,13.5,425916,159638,prior,2,6,15,30.0,8,0,both,Mid-range product,Regular busy,regular days
32404834,49688,Fresh Foaming Cleanser,73,11,13.5,2530161,163632,prior,1,3,12,NaN,1,0,both,Mid-range product,Regular busy,slowest days
32404835,49688,Fresh Foaming Cleanser,73,11,13.5,1288677,163632,prior,3,1,8,30.0,1,1,both,Mid-range product,Regular busy,busiest days
32404836,49688,Fresh Foaming Cleanser,73,11,13.5,3008450,164453,prior,6,0,12,5.0,8,0,both,Mid-range product,Busiest day,busiest days
32404837,49688,Fresh Foaming Cleanser,73,11,13.5,151501,166038,prior,2,2,16,10.0,4,0,both,Mid-range product,Regular busy,regular days
32404838,49688,Fresh Foaming Cleanser,73,11,13.5,2439935,166038,prior,7,4,21,30.0,9,1,both,Mid-range product,Least busy,slowest days
32404839,49688,Fresh Foaming Cleanser,73,11,13.5,1400940,166213,prior,1,1,21,NaN,4,0,both,Mid-range product,Regular busy,busiest days
32404840,49688,Fresh Foaming Cleanser,73,11,13.5,1219750,171743,prior,5,0,8,30.0,24,0,both,Mid-range product,Busiest day,busiest days
32404841,49688,Fresh Foaming Cleanser,73,11,13.5,307087,172262,prior,4,6,11,30.0,15,0,both,Mid-range product,Regular busy,regular days
32404842,49688,Fresh Foaming Cleanser,73,11,13.5,2454083,176942,prior,2,6,20,3.0,8,0,both,Mid-range product,Regular busy,regular days
32404843,49688,Fresh Foaming Cleanser,73,11,13.5,2710528,178693,prior,26,5,10,3.0,18,0,both,Mid-range product,Regular busy,regular days
32404844,49688,Fresh Foaming Cleanser,73,11,13.5,1173882,178752,prior,7,0,23,21.0,28,0,both,Mid-range product,Busiest day,busiest days
32404845,49688,Fresh Foaming Cleanser,73,11,13.5,1525694,178752,prior,15,5,10,30.0,3,1,both,Mid-range product,Regular busy,regular days
32404846,49688,Fresh Foaming Cleanser,73,11,13.5,2439069,182948,prior,4,6,16,13.0,1,0,both,Mid-range product,Regular busy,regular days
32404847,49688,Fresh Foaming Cleanser,73,11,13.5,2392655,182948,prior,8,2,11,16.0,28,1,both,Mid-range product,Regular busy,regular days
32404848,49688,Fresh Foaming Cleanser,73,11,13.5,848810,183548,prior,15,2,16,30.0,22,0,both,Mid-range product,Regular busy,regular days
32404849,49688,Fresh Foaming Cleanser,73,11,13.5,2251059,184081,prior,1,6,9,NaN,4,0,both,Mid-range product,Regular busy,regular days
32404850,49688,Fresh Foaming Cleanser,73,11,13.5,846716,187523,prior,14,3,11,9.0,8,0,both,Mid-range product,Regular busy,slowest days
32404851,49688,Fresh Foaming Cleanser,73,11,13.5,362546,188073,prior,5,2,4,30.0,4,0,both,Mid-range product,Regular busy,regular days
32404852,49688,Fresh Foaming Cleanser,73,11,13.5,3166828,188073,prior,7,1,15,30.0,5,1,both,Mid-range product,Regular busy,busiest days
32404853,49688,Fresh Foaming Cleanser,73,11,13.5,3106363,197371,prior,10,4,14,30.0,17,0,both,Mid-range product,Least busy,slowest days
32404854,49688,Fresh Foaming Cleanser,73,11,13.5,1788356,200215,prior,2,0,9,5.0,27,0,both,Mid-range product,Busiest day,busiest days
32404855,49688,Fresh Foaming Cleanser,73,11,13.5,3401313,200377,prior,1,4,11,NaN,5,0,both,Mid-range product,Least busy,slowest days
32404856,49688,Fresh Foaming Cleanser,73,11,13.5,809510,200873,prior,5,3,8,15.0,12,0,both,Mid-range product,Regular busy,slowest days
32404857,49688,Fresh Foaming Cleanser,73,11,13.5,2359893,200873,prior,9,3,15,5.0,11,1,both,Mid-range product,Regular busy,slowest days
32404858,49688,Fresh Foaming Cleanser,73,11,13.5,2385091,205926,prior,11,1,15,6.0,35,0,both,Mid-range product,Regular busy,busiest days

## Step 4: Finding busiest hours

In [37]:
# frequency of order hours of the day
ords_prods_merge['order_hour_of_day'].value_counts(dropna = False)

10    2761760
11    2736140
14    2689136
15    2662144
13    2660954
12    2618532
16    2535202
9     2454203
17    2087654
8     1718118
18    1636502
19    1258305
20     976156
7      891054
21     795637
22     634225
23     402316
6      290493
0      218769
1      115700
5       87961
2       69375
4       53242
3       51281
Name: order_hour_of_day, dtype: int64

In [38]:
ords_prods_merge.describe()

,product_id,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_the_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered
count,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.032876e+07,3.240486e+07,3.240486e+07
mean,2.559866e+04,7.119612e+01,9.919792e+00,1.198023e+01,1.710745e+06,1.029372e+05,1.714230e+01,2.738867e+00,1.342515e+01,1.110408e+01,8.352547e+00,5.895873e-01
std,1.408400e+04,3.821139e+01,6.281485e+00,4.956554e+02,9.872988e+05,5.946610e+04,1.753532e+01,2.090077e+00,4.246380e+00,8.779064e+00,7.127071e+00,4.919087e-01
min,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00
25%,1.354400e+04,3.100000e+01,4.000000e+00,4.200000e+00,8.559470e+05,5.142200e+04,5.000000e+00,1.000000e+00,1.000000e+01,5.000000e+00,3.000000e+00,0.000000e+00
50%,2.530200e+04,8.300000e+01,9.000000e+00,7.400000e+00,1.711049e+06,1.026160e+05,1.100000e+01,3.000000e+00,1.300000e+01,8.000000e+00,6.000000e+00,1.000000e+00
75%,3.794700e+04,1.070000e+02,1.600000e+01,1.130000e+01,2.565499e+06,1.543890e+05,2.400000e+01,5.000000e+00,1.600000e+01,1.500000e+01,1.100000e+01,1.000000e+00
max,4.968800e+04,1.340000e+02,2.100000e+01,9.999900e+04,3.421083e+06,2.062090e+05,9.900000e+01,6.000000e+00,2.300000e+01,3.000000e+01,1.450000e+02,1.000000e+00

Most orders hour frequency >= 1.6M, Average from 1.0M to 1.5M, Fewest < 1M

In [39]:
result = []

for value in ords_prods_merge ['order_hour_of_day']:
    if value in range(8, 18):
        result.append('Most orders')
    elif value in range(2,5):
        result.append('Fewest orders')
    else:
        result.append('Average orders')

In [40]:
ords_prods_merge['busiest_period_of_day'] = result

## Step 5

In [41]:
# printing frequency of new column
ords_prods_merge['busiest_period_of_day'].value_counts(dropna = False)

Most orders       24923843
Average orders     7307118
Fewest orders       173898
Name: busiest_period_of_day, dtype: int64

In [ ]:
ords_prods_merge.to_pickle('orders_products_insights.pkl')

In [42]:
ords_prods_merge.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_product_days_insights.pkl'))